### ISSUE TITLE
NVCC compile problem after adding void template parameter to Mult<> and Add<>

### ISSUE THREAD

**Issue by havogt** [havogt/symbolicmath#5]
Problem with binding the template parameters after Sort probably because of the additional template parameter `typename = void`.
The exactly same code snippet works with the same host compiler `g++-4.8.3`.
nvcc version: 7.5.

**Comment by havogt** [comment]
Error:

/home/vogt/git/symbolicmath/test/../include/helper/type_manipulation.h(35): error: too few arguments for template template parameter "Dest"
          detected during:
            instantiation of class "symbolicmath::Bind<Dest>::toTypesOf<Src<NewTs...>> [with Dest=symbolicmath::Add, Src=symbolicmath::TemporaryBindObject, NewTs=<V0, V1>]" 
(51): here
            instantiation of class "symbolicmath::BindList<List, Template> [with List=boost::mpl::v_item<V1, boost::mpl::v_item<V0, boost::mpl::vector0<mpl_::na>, 0>, 0>, Template=symbolicmath::Add]" 
/home/vogt/git/symbolicmath/test/../include/sort.h(28): here
            instantiation of class "symbolicmath::SortAndBind<Template, Ts...> [with Template=symbolicmath::Add, Ts=<V0, V1>]" 
/home/vogt/git/symbolicmath/test/../include/arithmetic.h(42): here
            instantiation of class "symbolicmath::Add<T1, T2, <unnamed>> [with T1=V0, T2=V1, <unnamed>=void]" 
/home/vogt/git/symbolicmath/test/test_eval.cu(10): here

/home/vogt/git/symbolicmath/test/test_eval.cu(10): error: name followed by "::" must be a class or namespace name

/home/vogt/git/symbolicmath/test/test_eval.cu(16): error: name followed by "::" must be a class or namespace name

**Comment by havogt** [comment]
fixed in 1186af0 (manually inject an additional void)
